//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasioCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class certificate
    {
        public long Certificateno { get; set; }
        public Nullable<long> Certino { get; set; }
    }
}
