//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasioCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class NewStudent
    {
        public long NewStudentID { get; set; }
        public string StudentName { get; set; }
        public string StudentPhoto { get; set; }
        public string FatherName { get; set; }
        public string FatherOccupation { get; set; }
        public string FatherPhoto { get; set; }
        public string MotherName { get; set; }
        public string MotherOccupation { get; set; }
        public string MotherPhoto { get; set; }
        public string GuardianName { get; set; }
        public string GuardianOccupation { get; set; }
        public string GuardianPhoto { get; set; }
        public string Gender { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<long> RegNumber { get; set; }
        public Nullable<System.DateTime> RegDate { get; set; }
        public Nullable<int> RegFee { get; set; }
        public Nullable<long> ClassID { get; set; }
        public string MobileNo { get; set; }
        public string PhoneNo { get; set; }
        public string Adress { get; set; }
        public Nullable<long> StateID { get; set; }
        public string City { get; set; }
        public string District { get; set; }
        public string PinCode { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public string TestTime { get; set; }
        public string AddInfo_ParentExStudent { get; set; }
        public string AddInfo_StaffChild { get; set; }
        public string AddInfo_ShiblingsDetails { get; set; }
        public string Religion { get; set; }
        public string Category { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Current_session { get; set; }
        public Nullable<long> Old_RegNo { get; set; }
        public string RegType { get; set; }
    }
}
