//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasioCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Student
    {
        public long StudentID { get; set; }
        public Nullable<long> AdmissionNo { get; set; }
        public string StudentName { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<System.DateTime> BOA { get; set; }
        public string FathersName { get; set; }
        public string FathersQualification { get; set; }
        public string FathersJob { get; set; }
        public string MothersName { get; set; }
        public string MothersQualification { get; set; }
        public string MothersJob { get; set; }
        public string PresentAddress { get; set; }
        public string PerminantAddress { get; set; }
        public string SessionOfAdmission { get; set; }
        public string PhoneNo { get; set; }
        public string Gender { get; set; }
        public Nullable<bool> Discharged { get; set; }
        public Nullable<long> TransportFee { get; set; }
        public string Phoneno2 { get; set; }
        public string landlineno { get; set; }
        public Nullable<long> StudentFeeRebate { get; set; }
        public Nullable<System.DateTime> WithdrawDate { get; set; }
        public Nullable<int> oldnewmigrated { get; set; }
        public Nullable<long> Ledgerid { get; set; }
        public Nullable<long> Saadhaarcard { get; set; }
        public Nullable<long> Faadhaarcard { get; set; }
        public Nullable<long> Maadhaarcard { get; set; }
        public string BankName { get; set; }
        public string AccountNo { get; set; }
        public string AccountType { get; set; }
        public string IFCCode { get; set; }
        public string Scategory { get; set; }
        public Nullable<long> ScategoryID { get; set; }
        public Nullable<int> BPLStatus { get; set; }
        public string SDisability { get; set; }
        public string Pincode { get; set; }
        public string Religion { get; set; }
        public string MotherTounge { get; set; }
        public string BloodGroup { get; set; }
        public string SEmail { get; set; }
        public string DateOfBirth { get; set; }
    }
}
