//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasioCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentInfo:Student
    {
        public long StudentInfoID { get; set; }
        public Nullable<long> StudentId { get; set; }
        public Nullable<long>  AdmissionNo { get; set; }
        public string Current_Session { get; set; }
        public Nullable<long> SessionID { get; set; }
        public Nullable<long> ClassID { get; set; }
        public Nullable<long> SectionID { get; set; }
        public Nullable<long> RouteID { get; set; }
        public Nullable<long> StreamID { get; set; }
        public string FeeBookNo { get; set; }
        public string BusFeeBookNo { get; set; }
        public string Remarks { get; set; }
        public string BoardNo { get; set; }
        public string Optional { get; set; }
        public string PrePrimaryBoardNo { get; set; }
        public Nullable<System.DateTime> PrePrimaryDate { get; set; }
        public string PrimaryBoardNo { get; set; }
        public Nullable<System.DateTime> PrimaryDate { get; set; }
        public string MiddleBoardNo { get; set; }
        public Nullable<System.DateTime> MiddleDate { get; set; }
        public string HighBoardNo { get; set; }
        public Nullable<System.DateTime> HighDate { get; set; }
        public string HigherBoardNo { get; set; }
        public Nullable<System.DateTime> HigherDate { get; set; }
        public byte[] Photo { get; set; }
        public string PhotoPath { get; set; }
        public string BusRoute { get; set; }
        public Nullable<long> OptionalID { get; set; }
        public Nullable<long> Rollno { get; set; }
        public Nullable<long> BusStopID { get; set; }
        public string SiblingID { get; set; }
        public Nullable<int> SiblingType { get; set; }
    }
}
