//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasioCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class StudentQuerry
    {
        public long SQID { get; set; }
        public Nullable<long> SIDFK { get; set; }
        public string SCode { get; set; }
        public string SQTitle { get; set; }
        public string SQRemarks { get; set; }
        public string SQFilePath { get; set; }
        public string SQBy { get; set; }
        public Nullable<System.DateTime> SQDate { get; set; }
        public Nullable<long> SQType { get; set; }
        public Nullable<int> SQStatus { get; set; }
        public string SQCloseBy { get; set; }
        public Nullable<System.DateTime> SQCloseDate { get; set; }
    }
}
