//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasioCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Classes
    {
        public long ClassId { get; set; }
        public string ClassName { get; set; }
        public string Current_Session { get; set; }
        public Nullable<long> SessionID { get; set; }
        public Nullable<long> SubDepartmentID { get; set; }
        public string ClassIncharg { get; set; }
        public string EduDepartmentName { get; set; }
    }
}
