//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasioCore
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Section
    {
        public long SectionID { get; set; }

        [Required]
        public string SectionName { get; set; }
        public Nullable<long> ClassId { get; set; }
        public string ClassName { get; set; }
        public Nullable<long> SessionId { get; set; }
        public string Current_Session { get; set; }
        public Nullable<int> IsFL { get; set; }
    }
}
