//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasioCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Session
    {
        public long SessionID { get; set; }
        public string Session1 { get; set; }
        public Nullable<System.DateTime> SessionFrom { get; set; }
        public Nullable<System.DateTime> SessionTo { get; set; }
        public Nullable<long> Current_Year { get; set; }
    }
}
