//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasioCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class OptionalSubject
    {
        public long OptionalSubjectID { get; set; }
        public string OptionalSubjectName { get; set; }
        public Nullable<long> ClassID { get; set; }
        public string Current_Session { get; set; }
        public Nullable<long> SessionID { get; set; }
    }
}
