//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasioCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Subject
    {
        public long SubjectID { get; set; }
        public string SubjectName { get; set; }
        public long ClassID { get; set; }
        public long SessionID { get; set; }
        public string Current_Session { get; set; }
        public long SectionID { get; set; }
    }
}
