//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasioCore
{
    using System;
    using System.Collections.Generic;
    
    public partial class Topic
    {
        public long TID { get; set; }
        public long ClassIDFK { get; set; }
        public long subjectIDFK { get; set; }
        public string TopicName { get; set; }
        public string UserName { get; set; }
       
    }
}
